# Generated by Django 5.0.6 on 2024-07-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfUrl', models.FileField(upload_to='documents/')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255, null=True)),
                ('accessLink', models.CharField(max_length=255, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
