# Generated by Django 5.0.6 on 2024-07-21 10:15
from ..utils.customStorages import CustomS3Boto3Storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='pdfUrl',
            field=models.FileField(storage=CustomS3Boto3Storage(), upload_to='documents/'),
        ),
    ]
